### ISSUE TITLE
Annotation reporting in Viewer

### ISSUE THREAD

**Issue by kaglowka** [PrzypisPowszechny/pp-client#104]

**Comment by glowka** [comment]
@KasiaSkowronska @kaglowka 

**What version are we implementing now?**
**1)** reporting with comment and reason  – If so mockup of dialogs and state of annotation after reporting is highly needed here.
_--OR--_
**2)**  reporting in upvote-like mode – If so mockup of state of annotation after reporting is needed, API also must be *slightly* adjusted, because we now require comment and reason to be filled in

**Comment by glowka** [comment]
Thanks for mockups and detailed description.

Regarding to:
> I guess for now we can think of "zasugeruj poprawki" as just another type (reason as you said) of report and we don't have to change anything in API?

We have *fixed* types, so just another type is still a change, but it's a small one.
